# Generated by Django 2.2.16 on 2022-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20220307_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, to='titles.Genres', verbose_name='Жанр'),
        ),
    ]
