# Generated by Django 2.2.16 on 2022-03-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ('-name',), 'verbose_name': 'Жанр произведения', 'verbose_name_plural': 'Жанр произведения'},
        ),
        migrations.RemoveField(
            model_name='genres',
            name='title',
        ),
        migrations.RemoveField(
            model_name='сategories',
            name='title',
        ),
        migrations.AddField(
            model_name='genres',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='сategories',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
