# Generated by Django 2.2.16 on 2022-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20220302_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сategories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
