# Generated by Django 2.2.16 on 2022-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20220302_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='titles.Genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
