# Generated by Django 2.2.16 on 2022-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20220302_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, to='titles.Genres', verbose_name='Жанр'),
        ),
    ]
